### ISSUE TITLE
set up a satellite-of-love REST service on Travis

### ISSUE THREAD

**Issue by jessitron** [satellite-of-love/berlin#16]
Created by Atomist Editor `PrepareTravisBuildFiles`
```
---
kind: "operation"
client: "atomist-bot"
editor:
  name: "PrepareTravisBuildFiles"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.10"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "c02132e"
  parameters:
    - "project": "workflow-rugs"
    - "encryptedGithubToken": "j**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "a**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "Y**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

```
        
Moved from https://github.com/satellite-of-love/workflow-rugs/pull/1
